export const GET_ALL_CURRENCY = "GET_ALL_CURRENCY "
export const GET_ALL_CURRENCY_REQUEST = "GET_ALL_CURRENCY_REQUEST"
export const GET_ALL_CURRENCY_RESPONSE = "GET_ALL_CURRENCY_RESPONSE"
export const GET_ALL_CURRENCY_ERRORS = "GET_ALL_CURRENCY_ERRORS"